mysql:
    restart: always
    image:  mysql
    container_name: mysql
    ports:
        - '3306:3306'
    volumes:
        - $PWD/mount/data/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        TZ: Asia/Chongqing

redis:
    image: redis:alpine
    container_name: redis
    ports:
        - "6379:6379"
    volumes:
        - $PWD/data/redis:/data
        - ./etc/redis/redis.conf:/etc/redis.conf
    command: ["redis-server", "/etc/redis.conf"]
    environment:
        TZ: Asia/Chongqing
    restart: always

php:
    restart: always
    image: aimsam/php7
    container_name: php
    links:
        - mysql
        - redis
    ports:
        - '9000:9000'
    volumes:
        - $PWD/mount/var/log:/var/log
        - ~/Projects:/var/htdocs
        - $PWD/images/php/7/local:/home/work/local
    environment:
        TZ: Asia/Chongqing
        REDIS_PORT: 6379

nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    links:
        - php
    ports:
        - '80:80'
        - '433:433'
    volumes:
        - ~/Projects:/var/htdocs
        - $PWD/mount/etc/nginx/conf.d:/etc/nginx/conf.d
        - $PWD/mount/etc/nginx/includes:/etc/nginx/includes
        - $PWD/mount/etc/nginx/sites-available:/etc/nginx/sites-available
        - $PWD/mount/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
        - $PWD/mount/var/log/nginx:/var/log/nginx
